version: '3.7'

services:
  remojobs_pg:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=root
    volumes:
      - ./docker-compose.init.sql:/docker-entrypoint-initdb.d/init.sql
